[package]
name = "t9"
version = "0.1.0"
authors = ["areille <areille@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.7.0"

[dependencies.gtk]
version = "0.6.0"
features = ["v3_16"]
